Update proposed Xdebug version to install
When trying to install Xdebug in a "development stage" as mentioned in the documentation, it fails with this error : 

```
+ pecl install xdebug-3.0.2
pecl/xdebug requires PHP (version >= 7.2.0, version <= 8.0.99), installed version is 8.1.1
No valid packages found
install failed
ERROR: Service 'php' failed to build: The command '/bin/sh -c set -eux;  apk add --no-cache --virtual .build-deps $PHPIZE_DEPS;  pecl install xdebug-$XDEBUG_VERSION;  docker-php-ext-enable xdebug;  apk del .build-deps' returned a non-zero code: 1
```

Updating the desired Xdebug version to 3.1.2 (latest as time of writing), fixes the problem.